config/routes.rb
Rails.application.routes.draw do
 # devise_for :users
 match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
 
resources :articles do
  
  resources :endorses
end
 
devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "home#index"
  resources :conversations, only: [:create] do
    member do
      post :close
    end
     resources :messages, only: [:create]
  end

resources :article do
  member do
    get "like", to: "articles#upvote"
    get "dislike", to: "articles#downvote"
  end
end

resources :users do
    resources :follows
end







namespace :api do

resources :oauth_callbacks, only: [] do 
      collection do 
        post '/facebook', to:  'oauth_callbacks#facebook'
        post '/google',   to:  'oauth_callbacks#google'
      end
    end
end













get "/tagging" => "articles#tag"
get "/user/profile" => "users#show"
get "/user/follow1111" => "users#follow"
get "/user/following" => "follows#following"
get "/user/follower" => "follows#follower"
get "/user/notification" => "users#notification"
get "/user/addfriend" => "users#friend"
get "/user/acc" => "users#accept_friend"
get "/user/de" => "users#delete_friend"


end


 
  

app/models/article.rb
class Article < ApplicationRecord
	  has_many :taggings
    has_many :users, through: :taggings
	 has_many :endorses
	 belongs_to :user
	  acts_as_votable
	    mount_uploader :img, AbcUploader
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
   include ApplicationHelper
  # GET /articles
  # GET /articles.json
  def tag
  
Tagging.create(:user_id => params[:userID ],article_id: params[:articleID ])


 redirect_to 'articles/#{:articleID}'
            

 
    
  end
  def index
    @articles = Article.all
 session[:conversations] ||= []
 
    @users = User.all.where.not(id: current_user)
    
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])


  end

  # GET /articles/1
  # GET /articles/1.json
  def show
     session[:conversations] ||= []
 
    @users = User.all.where.not(id: current_user)
    
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])

    @users=User.all
  end

  # GET /articles/new
  def new
   # byebug
  @articles = Article.all.order(created_at:  :desc)
 session[:conversations] ||= []
 
    @users = User.all
    
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])

    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  def dummy_def
    format.html { redirect_to new_article_path, notice: 'Article was successfully created.' }
    format.json { render :show, status: :created, location: @article }
    format.html { render :new }
    format.json { render json: @article.errors, status: :unprocessable_entity }
  end

  # POST /articles
  # POST /articles.json
  def create
    
    @article = Article.new(article_params)
    @article.user_id=current_user.id
    

  
    respond_to do |format|
      if @article.save
        byebug
        @art_id= @article.id
       @user_idss = params[:vvv ]
       if @user_idss != nil
         
     
        @user_idss.each do |userid|
         Tagging.create(:user_id => userid,article_id: @art_id) 
  
        end
          end
        #Tagging.create(:user_id => params[:abc ],article_id: @art_id)
                #UserMailer.welcome_email(current_user).deliver_now

        format.html { redirect_to new_article_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



    def upvote
             @articles =    Article.all
      @article = Article.find(params[:id])
      @article.liked_by current_user
      Notification.create(recipient_id: @article.user.id, actor_id: current_user.id, article_id: @article.id, notifiable_for: "like")
       respond_to do |format|
    format.js {} #render :file => 'articles/article.js.erb'}
     end
  end
 def downvote
               @articles =    Article.all

      @article = Article.find(params[:id])
      @article.downvote_from current_user


      Notification.create(recipient_id: @article.user.id, actor_id: current_user.id, article_id: @article.id, notifiable_for: "dislike")
       respond_to do |format|
    format.js {                } #render :file => 'articles/article.js.erb'}
     end
  end







  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :img)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	 

end

app/views/articles/_form.html.erb
 

<!DOCTYPE html>
<html>
<head>

</head>
<body >
    <div class="container">
      <div class="container bgbox2">
        <div class="col-md-9 ">
          <p>COLAB</p>
        </div>
        <div class="col-md-3">
          <a href=""><img src="/images/message.png" class="img" alt="Cinque Terre" ></a>
          <a href=""><img src="/images/well.png" class="img" alt="Cinque Terre" ></a>
          <a href=""><img src="/images/profile.png" class="img" alt="Cinque Terre" ></a> 
        </div>
      </div>
    </div>
    <br/>
    <div class="container">
      <div class="col-md-4">
       

         <%=image_tag current_user.img, class: "img-circle" , alt: "Cinque Terre" ,size: 10*10%>
           <div ><%=current_user.name%></div>
      </div>

      <div class="col-md-8">
        <div class="well well-sm  ">


              <%= form_with(model: article, local: true) do |form| %>
                 
                <div class="emoji-picker-container">
                  <%= form.label :title %>
                  <%= form.text_field :title,class: "img-responsive posi" ,width: "1000" ,alt: "Cinque Terre", data: { emojiable: true } %>
                </div><br>
                  <%= form.label :Tag %><br>
              <select multiple class="js-example-basic-multiple"   name="vvv[]"
                style="width: 11.75em;">
                              <% @users.each do |user| %>
                        <option value= "<%=user.id%>"><%=user.name%></option>
                              <% end %>

                        </select>
                
                  
               
                  <%= form.label :img_upload %>
                  <%= form.file_field :img,  src: "/images/attch.png" , class: "img-responsive posi1" ,alt: "Cinque Terre" %>

            
                
          <a href=""><img src="/images/attch.png" class="img-responsive posi1" alt="Cinque Terre" ></a>
                 
          
            




        
        </div>
        <br/>
        <div class="btn-group">
         
           <%= form.submit "Post Article" ,style: "padding:5px 60px;" ,class: "btn  " %>
            <% end %>
        </div>
      </div>
    </div>
    <hr/>
    </body>


</html>

  

<!-- <head>
<script>
       // $("#e122").select2();

       $( "#e122" ).select2({
            theme: "bootstrap"
        });
    </script>
</head> -->

<script type="text/javascript">
$(".js-example-basic-multiple").select2({
            theme: "bootstrap",  multiple: true
        });
</script>

<!-- <select class="js-example-basic-multiple" multiple="multiple">
  <option value="AL">Alabama</option>
    ...
  <option value="WY">Wyoming</option>
</select> -->

app/views/articles/_index.html.erb
<h1>Articles</h1>

    <div class="container">
    <div class="container">
      <% @articles.each do |article| %>
      <div class="col-md-12">
         <%= image_tag article.img ,size: 10*6  %>
          







        <%#=article.user.name%>
        <br/>
        <div class="well well-sm "><%= article.title %></div>
           <div class="well well-sm  ">
          <%= link_to 'Show', article %>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to 'Edit', edit_article_path(article) %>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>&nbsp;&nbsp;&nbsp;&nbsp;

            
              <%#@likes=Vote.where(votable_id: article.id ,vote_flag: true).count%>

               <%#@dislikes=article.get_downvotes.size%>
          <%# if Vote.find_by(votable_id: article.id).present? %>
            <%# if Vote.where(votable_type: "Article", voter_id: current_user.id, vote_flag: "t").first.present? %>
            <%#= link_to "Dislike #{@dislikes}", dislike_article_path(article), method: :put %>
            <%#else%>
            <%#= link_to "Like #{@likes}", like_article_path(article), method: :put %>
        
             <a id="asheesh<%=article.id%>" href="#">
               
             </a>
         <%= link_to "Like #{article.get_upvotes.size}" , like_article_path(article) ,  :remote=> true, class: "btn btn-primary", id: "xxxx#{article.id}"     %>
      
     

          <!-- <span class="article-up-<%=article.id%>" style='width: 50px' >
             Like<%#= article.get_upvotes.size %><%# end %></td>
          </span>
        -->
       
          <a id="asheesh_mourya<%=article.id%>" href="#">
               
             </a>
          <%= link_to "Dislike #{article.get_downvotes.size}" , dislike_article_path(article), :remote=> true ,class: "btn btn-primary", id: "yyyy#{article.id}" %>
        
          
            <%# end %>
          <%#byebug%>
          <%#= link_to "Like", like_article_path(article), method: :put %> 
          <%#= link_to "Dislike", dislike_article_path(article), method: :put %>
          <%#else%>
          <%#= link_to "Like", like_article_path(article), method: :put %>
          <%#= link_to "Dislike", dislike_article_path(article), method: :put %>
          <%# end %>
          &nbsp;&nbsp;&nbsp;&nbsp;
           
          <button  onclick="endorses_click('<%=article.id%>');">Endorse</button>
           &nbsp;&nbsp;&nbsp;&nbsp;

          <!-- <button  onclick="chat_click('<%=article.id%>');">Connect</button>&nbsp;&nbsp;&nbsp;&nbsp; -->


          <a href="">
          unlike (0)
          </a>&nbsp;&nbsp;&nbsp;&nbsp;
        </div>
















     











 
           <h2>endorses</h2>
           <div id = "abc-<%= article.id%>">
                <% article.endorses.each do |endorse| %> 
                  
                
                  <p>
                    <strong>body:</strong>
                    <%= endorse.body %>
                  </p>

                 
                <% end %>
                </div>
                 <div id="endorse_form_<%=article.id %>" style='display: none;'>
                  <h2>Add a endorse:</h2>
                  <%= form_for([article, article.endorses.build], remote: true) do |f| %>
                    <!-- <p>
                      <%#= f.label :title %><br>
                      <%#= f.text_field :title %>
                    </p> -->
                    <p>
                      <%= f.label :body %><br>
                      <%= f.text_area :body , id: "asheesh1-#{article.id}"%>
                    </p>
                    <p>
                      <%= f.submit %>
                    </p>
                  <% end %>
                </div>



           <h2>Users Tagged</h2>
                <% article.taggings.each do |tagging| %> 
                  <p>
                  
                    <%= User.find(tagging.user_id).name %>
                  </p>
                 
                 
                <% end %>

      </div>
      <% end %>
      <div>
      </div>
    </div>


<script>

function endorses_click(argument) {

   $("#endorse_form_"+ argument).toggle();
}

</script>
    
    <script>

function chat_click(argument) {
   $(".chat_form_"+ argument).toggle();
}

</script>

app/views/articles/_upvote.html.erb
 <%= link_to "Like #{article.get_upvotes.size}" , like_article_path(article) ,  :remote=> true, class: "btn btn-primary", id: "xxxx#{article.id}"     %>

app/views/articles/article.js.erb
alert("hiiii")
$(function() { 
	
  $('.article-up-<%=@article.id%>').text( "Like"+"<%= @article.get_upvotes.size %>" );
  $('.article-down-<%=@article.id%>').text("Dislike"+"<%= @article.get_downvotes.size %>" );
});

app/views/articles/downvote.js.erb
//alert("hello0000000000000111111");
//debugger
alert("hiiiiiiiiiiii");
 $("#hello<%=@article.id%>").html('<a data-remote="true" class="btn btn-primary" href="/article/<%=@article.id%>/like"  >Like <%=@article.get_upvotes.size%></a>');
$("#hi<%=@article.id%>").html('<a class="btn btn-primary" href="/article/<%=@article.id%>/dislike">Dislike <%=@article.get_downvotes.size%></a>');
//var b = a.split(' ');
//b[1]
//var cc=parseInt(b[1]);
//debugger
// if(cc == <%#=@article.get_upvotes.size%>){
// 	//alert("hiiiii")
// 	var d = $("#hi").text();
// var e = d.split(' ');
// //debugger
// var e=parseInt(e[1]);
// $("#hi").text("dislike" + e+1)	
// }


//$("#hello").text()

//all commented code are working
$("<%=j render(:partial => 'articles/index', :object => @articles) %>")

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
body {
    background-image: url("/images/lamborgini.png");
     background-repeat: no-repeat;
    background-position: right top;
    margin-right: 200px;
    background-attachment: fixed;
}
 .abc{
    color: green;
}
</style>
</head>

<body>
<p id="notice"><%= notice %></p>
<h1>Articles</h1>
<!-- <table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Article', new_article_path %> -->








<!DOCTYPE html>
<html lang="en">
  <head>
    <title>stream-page</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div class="container">
    <div class="container">
      <% @articles.each do |article| %>
      <div class="col-md-12">
        <a href=""><img src="images/Generic-profile-image.png" class="img" alt="Cinque Terre" width="60" hight="60"></a><a href="">User Name</a>
        <br/>
        <div class="well well-sm "><%= article.title %></div>
         
             




        <div class="well well-sm  ">
          <%= link_to 'Show', article %>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to 'Edit', edit_article_path(article) %>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>&nbsp;&nbsp;&nbsp;&nbsp;

            
              <%#@likes=Vote.where(votable_id: article.id ,vote_flag: true).count%>

               <%#@dislikes=article.get_downvotes.size%>
          <%# if Vote.find_by(votable_id: article.id).present? %>
            <%# if Vote.where(votable_type: "Article", voter_id: current_user.id, vote_flag: "t").first.present? %>
            <%#= link_to "Dislike #{@dislikes}", dislike_article_path(article), method: :put %>
            <%#else%>
            <%#= link_to "Like #{@likes}", like_article_path(article), method: :put %>






   
       
         <td><%= link_to  like_article_path(article), method: :put ,data: { :remote=> true }  do %>
          <span class="article-up-<%=article.id%>" style='width: 50px' >
             Like<%= article.get_upvotes.size %><% end %></td>
          </span>
       
          <td><%= link_to  dislike_article_path(article), method: :put ,data: { :remote=> true }  do %>
          <span class="article-down-<%=article.id%>" style='width: 50px'>
           Dislike<%= article.get_downvotes.size %><% end %></td>
          </span>
    
   

         






            <%# end %>
          <%#byebug%>
          <%#= link_to "Like", like_article_path(article), method: :put %> 
          <%#= link_to "Dislike", dislike_article_path(article), method: :put %>
          <%#else%>
          <%#= link_to "Like", like_article_path(article), method: :put %>
          <%#= link_to "Dislike", dislike_article_path(article), method: :put %>
          <%# end %>
          &nbsp;&nbsp;&nbsp;&nbsp;
           
          <button  onclick="endorses_click('<%=article.id%>');">Endorse</button>
           &nbsp;&nbsp;&nbsp;&nbsp;

          <!-- <button  onclick="chat_click('<%=article.id%>');">Connect</button>&nbsp;&nbsp;&nbsp;&nbsp; -->


          <a href="">
          unlike (0)
          </a>&nbsp;&nbsp;&nbsp;&nbsp;
        </div>







<div class="chat_form_<%=article.id %>" style='display: none;'>
    
<div class="row">
  <div class="col-md-9">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">User list</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @users.each do |user| %>
         <li><%= link_to user.email, conversations_path(user_id: user), remote: true, method: :post %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
     </div>













     












           <h2>endorses</h2>
                <% article.endorses.each do |endorse| %> 
                  <p>
                    <strong>title:</strong>
                    <%= endorse.title %>
                  </p>
                 <div class="abc">
                  <p>
                    <strong>body:</strong>
                    <%= endorse.body %>
                  </p>
                  </div>

                  <p>
                    <strong>Endorsed by:</strong>
                    <%= endorse.user.email %>
                  </p>
                <% end %>
                 <div class="endorse_form_<%=article.id %>" style='display: none;'>
                  <h2>Add a endorse:</h2>
                  <%= form_for([article, article.endorses.build]) do |f| %>
                    <p>
                      <%= f.label :title %><br>
                      <%= f.text_field :title %>
                    </p>
                    <p>
                      <%= f.label :body %><br>
                      <%= f.text_area :body %>
                    </p>
                    <p>
                      <%= f.submit %>
                    </p>
                  <% end %>
                </div>

      </div>
      <% end %>
      <div>
      </div>
    </div>
  </body>
</html>

<script>

function endorses_click(argument) {
   $(".endorse_form_"+ argument).toggle();
}

</script>
    
    <script>

function chat_click(argument) {
   $(".chat_form_"+ argument).toggle();
}

</script>

app/views/articles/new.html.erb
<center><h1>New Article</h1></center>



<%= render 'form', article: @article %>
<%= render 'index' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <td>
      <p>
        <strong>Title:</strong>
        <%= content_with_emoji(@article.title) %>

       
      </p>
      <p>
        <strong>image:</strong>
        <%= image_tag@article.img %>

       
      </p>
    </td>
<%  @users.each do |user| %>
    <td>
      <p>
        <strong>Tag To User:</strong>
            <td><%= link_to user.email, tagging_path+ "?userID=#{user.id}&&articleID=#{@article.id}"  %></td>


      </p>
    </td>
    <% end %>

    <% if Vote.find_by(votable_id: @article.id).present? %>

	    <% if @article.votes_for.where(voter_id: current_user.id).first.vote_flag == true %>
	    <td><%= link_to "Dislike", dislike_article_path(@article), method: :put %></td>
	    <%else%>
	    <td><%= link_to "Like", like_article_path(@article), method: :put %></td>
	    <% end %>
      <%else%>
      <td><%= link_to "Like", like_article_path(@article), method: :put %></td>
    <td><%= link_to "Dislike", dislike_article_path(@article), method: :put %></td>
    <% end %>
    
  </tr>
  <tr>
    <h2>endorses</h2>
<% @article.endorses.each do |endorse| %> 
  <p>
    <strong>title:</strong>
    <%= endorse.title %>
  </p>
 
  <p>
    <strong>body:</strong>
    <%= endorse.body %>
  </p>

  <p>
    <strong>Endorsed by:</strong>
    <%= endorse.user.email %>
  </p>
<% end %>
 
<h2>Add a endorse:</h2>
<%= form_for([@article, @article.endorses.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>


  </tr>
</table>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>



















<div class="row">
  <div class="col-md-9">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">User list</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @users.each do |user| %>
         <li><%= link_to user.email, conversations_path(user_id: user), remote: true, method: :post %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/articles/upvote.js.erb
$('#asheesh<%=@article.id%>').html("<%= j render partial: 'upvote', locals: { article: @article} %>");
$('#xxxx<%=@article.id%>').hide();