config/routes.rb
Rails.application.routes.draw do
 # devise_for :users
 match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
 
resources :articles do
  
  resources :endorses
end
 
devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "home#index"
  resources :conversations, only: [:create] do
    member do
      post :close
    end
     resources :messages, only: [:create]
  end

resources :article do
  member do
    get "like", to: "articles#upvote"
    get "dislike", to: "articles#downvote"
  end
end

resources :users do
    resources :follows
end







namespace :api do

resources :oauth_callbacks, only: [] do 
      collection do 
        post '/facebook', to:  'oauth_callbacks#facebook'
        post '/google',   to:  'oauth_callbacks#google'
      end
    end
end













get "/tagging" => "articles#tag"
get "/user/profile" => "users#show"
get "/user/follow1111" => "users#follow"
get "/user/following" => "follows#following"
get "/user/follower" => "follows#follower"
get "/user/notification" => "users#notification"
get "/user/addfriend" => "users#friend"
get "/user/acc" => "users#accept_friend"
get "/user/de" => "users#delete_friend"


end


 
  

app/models/user.rb
class User < ApplicationRecord
   mount_uploader :img, AbcUploader
    has_many :taggings
    has_many :articles, through: :taggings
has_many :articles
    has_many :endorses
has_many :messages
has_many :conversations, foreign_key: :sender_id

has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        # user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup, :follow]


def friend
      if Friendship.where(sender: current_user.id,receiver: params[:id], accept: false).first.present?
          flash[:notice] = "you have already sent the friend  request to this user"

      elsif Friendship.where(sender: current_user.id,receiver: params[:id], accept: true).first.present?
       
            flash[:notice] = "You are already friend of this user"  
        else
            Friendship.create(sender: current_user.id,receiver: params[:id], accept: false )
            flash[:notice] = "freind request sent"  
        end
  
   redirect_to user_profile_path(id: current_user.id)
end

def accept_friend
  @abc=Friendship.where(receiver: params[:re] ,sender: params[:se]).first
  @abc.update(accept: true)
      flash[:notice] = "Now you are friend with #{User.where(id: params[:se]).first.name}"
    redirect_to user_profile_path(id: current_user.id)
end
def delete_friend
  @abc=Friendship.where(receiver: params[:re] ,sender: params[:se]).first
  @abc.destroy
   flash[:notice] = "request deleted"
  redirect_to user_profile_path(id: current_user.id)
end
  def notification

   @likenotifications= Notification.where(recipient_id: current_user.id,notifiable_for: "like")
    @dislikenotifications= Notification.where(recipient_id: current_user.id,notifiable_for: "dislike")
    
  end

  # GET /users/:id.:format
  def show
   if Friendship.where(receiver: current_user.id).first.present?
      @friend_request=Friendship.where(receiver: current_user.id)
    end 

     @users = User.all.where.not(id: current_user)
    
      

    if Friendship.where(receiver: current_user.id).first.present? || Friendship.where(sender: current_user.id).first.present?

      @friends = Friendship.where(receiver: current_user.id)
    
       @friends1 = Friendship.where(sender: current_user.id)
    end

  end
  def follow
  
  
    Follow.create(follower_id: params[:followerid], following_id: params[:followingid] )

    redirect_to user_profile_path
    
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
  
    
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(email:  params[:user][:email])
        # @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to new_article_path, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
    def set_user
       
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/notification.html.erb
<% @likenotifications.each do |notf| %>
<%@user=User.where(id: notf.actor_id).first%>
<%@title=Article.where(id: notf.article_id).first.title%>
<%if @user != current_user%>

  <p>
 
    <%= "#{@user.name} liked your atricle #{@title} #{notf.id}" %>
  </p>
 <% end %>
 
<% end %>

app/views/users/show.html.erb
<h1>Your profile</h1>
<h3><%= link_to "Notifications", user_notification_path %></h3><br>

<h3><%#= link_to "Add a Friend", "#abb", data: {toggle: "collapse"} , data: {target: "#demo"} %></h3>

 <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo1">your friends</button> <br>
<div class="container">
<div id="demo1" class="collapse">
      <%if @friends !=nil%>
          <%  @friends.each do |friend| %>
           <%= User.where(id: friend.sender).first.name %>
          <% end %>
      <% end %>
      <%if @friends1 !=nil%>
            <%  @friends1.each do |friend| %>
             <%= User.where(id: friend.receiver).first.name %>
            <% end %>
      <% end %>
</div>
</div>













  <br><button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">Add a friend</button>  
<div class="container">
<div id="demo" class="collapse">
  
<% @users.each do |user| %>
  <p>
  
    <%= user.name %>
    <%= link_to "Add Friend", user_addfriend_path(id: user.id) %>
  </p>
 
<% end %>
<%if @friend_request !=nil%>

<%  @friend_request.each do |frr| %>
  <p>
     <%unless frr.accept==true&&frr !=nil%>
     <%@userr=User.where(id: frr.sender).first%>
    <%= "u have a friend request from #{@userr.name }" %>
    <%= link_to "accept", user_acc_path(re: current_user.id,se: @userr.id) %>
    
  <%= link_to "delete", user_de_path(re: current_user.id,se: @userr.id) %>
    <%end%>
  </p>
 
  
<% end %>
<% end %>

 </div>
</div>

  

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Profile first login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body style="padding-top:50px;">
 <div class="container">
  <div align="right">
  <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-success" %>
</div>
 </div>

    <div class="container">
      <center>
       
        <%=image_tag current_user.img, class: "img-circle" , alt: "Cinque Terre" ,size: 10*10%>
        <div   ><%=current_user.name%></div>

      </center>
    </div>
    <div class="continer my-continer padd2">
     

       <p >email</p>
     <div class="well well-sm  "><%=current_user.email%></div>
       <p >About</p>
     <div class="well well-sm  "><%=current_user.about%></div>
     
      <div class="btn-group">
        <p>Intrest</p>
        <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Design</button>
        <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Art</button>
        <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Graphics</button>
        <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Music</button>
        <button style="padding:50px 60px;margin-left:30px;" type="button" class="btn">Drama</button>
      </div>
      <br/><br/><br/>
      <div class="container">
        <div class="col-md-10">
          <center><button style="padding:5px 60px;" type="button" class="btn">Next</button></center>
        </div>
        <div class="col-md-2">
          <p class="alinright"> <a href="">Skip This</a></p>
        </div>
      </div>
    </div>
  </body>
</html>